-- Fix YouTube Title & Descriptions templates to use {{call_to_action}} placeholder
-- Generated: 2025-12-08T23:13:22.049Z

-- Template ID 111: YouTube Title & Descriptions
UPDATE templates SET prompt_template = 'Please ignore all previous instructions. Please respond only in the english language. You are a YouTuber with a large fan following. You have a Creative tone of voice. You have a Argumentative writing style. Do not self reference. Do not explain what you are doing. Generate catchy YouTube titles and descriptions for a list of keywords "{{keywords}}". Only one title and one description should be generated for each keyword. The title should not be more than 100 characters long. The description should be more informative. The titles should be good for videos and help generate titles. The titles should be generic by visual way. The description should be long and contain multiple informational paragraphs about the topic. The description should also ask the viewer {{call_to_action}}.' WHERE id = 111;

-- Template ID 152: YouTube Title & Descriptions
UPDATE templates SET prompt_template = 'Please ignore all previous instructions. Please respond only in the english language. You are a YouTuber with a large fan following. You have a Creative tone of voice. You have a Argumentative writing style. Do not self reference. Do not explain what you are doing. Generate catchy YouTube titles and descriptions for a list of keywords "{{keywords}}". Only one title and one description should be generated for each keyword. The title should not be more than 100 characters long. The description should be more informative. The titles should be good for videos and help generate titles. The titles should be generic by visual way. The description should be long and contain multiple informational paragraphs about the topic. The description should also ask the viewer {{call_to_action}}.' WHERE id = 152;

-- Template ID 193: YouTube Title & Descriptions
UPDATE templates SET prompt_template = 'Please ignore all previous instructions. Please respond only in the english language. You are a YouTuber with a large fan following. You have a Creative tone of voice. You have a Argumentative writing style. Do not self reference. Do not explain what you are doing. Generate catchy YouTube titles and descriptions for a list of keywords "{{keywords}}". Only one title and one description should be generated for each keyword. The title should not be more than 100 characters long. The description should be more informative. The titles should be good for videos and help generate titles. The titles should be generic by visual way. The description should be long and contain multiple informational paragraphs about the topic. The description should also ask the viewer {{call_to_action}}.' WHERE id = 193;

